version: '3.7'

services:
  pwgan-serving:
    image: airenas/pwgan-pytorch-serving:${SERVICE_VERSION}
    ports:
      - "${SERVICE_PORT}:8000"
    environment:
      MODEL_NAME: ${MODEL_NAME}
      MODEL_PATH: "/model"
    # restart: unless-stopped
    volumes:
      - ${MODEL_PATH}:/model
